version: '3.9'

services:
  database:
    image: ghcr.io/ferretdb/ferretdb:1.21.0
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://username:password@postgres/ferretdb
      FERRETDB_LOG_LEVEL: error
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ferretdb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
