version: "3.9"

services:
  nightscout-ferretdb:
    image: nightscout-ferretdb
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # Nightscout 
      CUSTOMCONNSTR_mongo: mongodb://localhost:27017/nightscout
      API_SECRET: 1234567890abc
      HOSTNAME: 0.0.0.0
      ENABLE: "devicestatus rawbg upbat careportal iob profile cage bage avg cob basal treatments sage boluscalc pump openaps iage speech"
      SHOW_PLUGINS: "rawbg-on careportal upbat iob profile cage cob basal avg treatments boluscalc pump openaps iage speech"
      TIME_FORMAT: 24
      ALARM_TYPES: "predict"
      LANGUAGE: en
      INSECURE_USE_HTTP: true
      PORT: 1337
      NODE_ENV: development
      AUTH_FAIL_DELAY: 50

      # FerretDB
      # FERRETDB_HANDLER: sqlite
      FERRETDB_POSTGRESQL_URL: postgres://username:password@postgres/ferretdb
      FERRETDB_LOG_LEVEL: error
    ports:
      - 1338:1337
    depends_on:
      - postgres
    # volumes:
      # - ./volumes/sqlite/state:/nightscout-ferretdb/data/state
  
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ferretdb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      